In [2]:
import pandas as pd

In [24]:
Student_Data = pd.read_csv("Student_Marks_Practise.csv",na_values=["abcent"])
Student_Data

           roll_no                  name  quiz_1  quiz_2  quiz_3  final_exam
0    SMIT/DSAI/001         Thomas Mcneil     6.0     1.0     6.0         6.0
1    SMIT/DSAI/002       Brian Davis Jr.     3.0     2.0     7.0         3.0
2    SMIT/DSAI/003  Christopher Thompson    10.0     8.0     2.0         7.0
3    SMIT/DSAI/004          Thomas Ortiz     7.0    -2.0     5.0        19.0
4    SMIT/DSAI/005      Benjamin Aguirre     4.0     3.0     0.0        28.0
..             ...                   ...     ...     ...     ...         ...
495  SMIT/DSAI/496           Rita Torres     9.0     9.0     7.0         NaN
496  SMIT/DSAI/497           Paul Thomas     7.0     8.0     7.0         NaN
497  SMIT/DSAI/498           Jacob Simon     9.0     1.0    10.0        10.0
498  SMIT/DSAI/499        Kimberly Ayers     9.0     7.0     1.0         3.0
499  SMIT/DSAI/500           Alvin Brown     9.0     7.0     8.0         NaN

[500 rows x 6 columns]

In [25]:
Student_Data.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   roll_no     500 non-null    str
 1   name        500 non-null    str
 2   quiz_1      450 non-null    float64
 3   quiz_2      450 non-null    float64
 4   quiz_3      451 non-null    float64
 5   final_exam  450 non-null    float64
dtypes: float64(4), str(2)
memory usage: 23.6 KB

In [26]:
Student_Data.describe()

           quiz_1      quiz_2      quiz_3  final_exam
count  450.000000  450.000000  451.000000  450.000000
mean     4.808889    4.895556    4.931264   19.737778
std      3.161420    3.143945    3.184291   12.158114
min      0.000000   -2.000000   -1.000000  -34.000000
25%      2.000000    2.000000    2.000000   10.000000
50%      5.000000    5.000000    5.000000   19.000000
75%      7.000000    8.000000    7.500000   30.000000
max     10.000000   10.000000   10.000000   40.000000

In [27]:
Student_Data.isna()

     roll_no   name  quiz_1  quiz_2  quiz_3  final_exam
0      False  False   False   False   False       False
1      False  False   False   False   False       False
2      False  False   False   False   False       False
3      False  False   False   False   False       False
4      False  False   False   False   False       False
..       ...    ...     ...     ...     ...         ...
495    False  False   False   False   False        True
496    False  False   False   False   False        True
497    False  False   False   False   False       False
498    False  False   False   False   False       False
499    False  False   False   False   False        True

[500 rows x 6 columns]

In [28]:
Student_Data.duplicated().sum()

np.int64(0)

In [29]:
obtain_marks = Student_Data.sum

In [30]:
Student_Data["Obtain Marks"] = Student_Data.iloc[:,2:].sum(axis=1)
Student_Data

,roll_no,name,quiz_1,quiz_2,quiz_3,final_exam,Obtain Marks
0,SMIT/DSAI/001,Thomas Mcneil,6.0,1.0,6.0,6.0,19.0
1,SMIT/DSAI/002,Brian Davis Jr.,3.0,2.0,7.0,3.0,15.0
2,SMIT/DSAI/003,Christopher Thompson,10.0,8.0,2.0,7.0,27.0
3,SMIT/DSAI/004,Thomas Ortiz,7.0,-2.0,5.0,19.0,29.0
4,SMIT/DSAI/005,Benjamin Aguirre,4.0,3.0,0.0,28.0,35.0
...,...,...,...,...,...,...,...
495,SMIT/DSAI/496,Rita Torres,9.0,9.0,7.0,NaN,25.0
496,SMIT/DSAI/497,Paul Thomas,7.0,8.0,7.0,NaN,22.0
497,SMIT/DSAI/498,Jacob Simon,9.0,1.0,10.0,10.0,30.0
498,SMIT/DSAI/499,Kimberly Ayers,9.0,7.0,1.0,3.0,20.0
499,SMIT/DSAI/500,Alvin Brown,9.0,7.0,8.0,NaN,24.0

In [31]:
Student_Data["Total"] = 100.0